print("##########################")
print("#                        #")
print("#  RABIAH RISKA AMALIAH  #")
print("#     2410817320010      #")
print("#                        #")
print("##########################")